## Test 3.0


In [1]:
num = int(input("Enter a number: "))

if num % 2 == 0:
    print(f"{num} is Even.")
else:
    print(f"{num} is Odd.")


Enter a number:  3


3 is Odd.


In [2]:
for i in range(10, 0, -1):
    print(i)


10
9
8
7
6
5
4
3
2
1


In [3]:
number = int(input("Enter a number (0 to stop): "))

while number != 0:
    print(f"You entered: {number}")
    number = int(input("Enter a number (0 to stop): "))

print("You entered 0. Program ended.")


Enter a number (0 to stop):  3


You entered: 3


Enter a number (0 to stop):  8


You entered: 8


Enter a number (0 to stop):  0


You entered 0. Program ended.


In [4]:
def add_numbers(a, b):
    return a + b

result = add_numbers(5, 7)
print("The sum is:", result)


The sum is: 12


In [ ]:
What will be the output of this code: print(list(map(lambda x: x*x, [1, 2, 3])))?

In [ ]:
[1, 4, 9]


In [5]:
numbers = [1, 2, 3, 4, 5, 6]

even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

print(even_numbers)


[2, 4, 6]


Explain the purpose of the else block in a try-except-else construct.

In [ ]:
The else block in a try-except-else construct in Python serves a specific purpose: it executes only if the try block completes without raising any exceptions.

In [8]:
try:
    numerator = int(input("Enter numerator: "))
    denominator = int(input("Enter denominator: "))
    result = numerator / denominator
    print("Result:", result)
except ZeroDivisionError:
    print("Error: Cannot divide by zero.")

Enter numerator:  2
Enter denominator:  0


Error: Cannot divide by zero.


In [ ]:
8

In [9]:
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print(f"{self.name} says: Woof!")

my_dog = Dog("Buddy", "Golden Retriever")
print(f"My dog's name is {my_dog.name} and breed is {my_dog.breed}.")
my_dog.bark()


My dog's name is Buddy and breed is Golden Retriever.
Buddy says: Woof!


In [10]:
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print(f"{self.name} says: Woof!")

dog1 = Dog("Max", "Labrador")
dog2 = Dog("Bella", "Beagle")


print(f"{dog1.name} is a {dog1.breed}.")
dog1.bark()

print(f"{dog2.name} is a {dog2.breed}.")
dog2.bark()


Max is a Labrador.
Max says: Woof!
Bella is a Beagle.
Bella says: Woof!


In [ ]:
Class variables are shared by all objects of a class; instance variables are unique to each object.

In [11]:
print("apple" if 5 > 3 else "banana")


apple


In [12]:
def get_squares(numbers):
    return [x ** 2 for x in numbers]

numbers = [1, 2, 3, 4, 5]
squares = get_squares(numbers)
print("List of squares:", squares)


List of squares: [1, 4, 9, 16, 25]


In [ ]:
map(): It returns an iterator that applies a given function to each item in the iterable. We need to convert it to a list (or other collection) to view the results.

In [ ]:
filter(): It returns an iterator that contains only the items for which the given function returns True

### Numpy

In [13]:
import numpy as np

matrix = np.random.randint(0, 10, (3, 3))
print(matrix)

[[9 1 6]
 [1 8 0]
 [4 6 1]]


In [14]:
first_two_rows = matrix[:2, :]
print(first_two_rows)

[[9 1 6]
 [1 8 0]]


Combine two 3x3 matrices using np.concatenate along axis 0 and axis 1.

In [15]:
matrix2 = np.random.randint(0, 10, (3, 3))
print("First Matrix:\n", matrix)
print("\nSecond Matrix:\n", matrix2)

matrix_combined_axis0 = np.concatenate((matrix, matrix2), axis=0)
print("\nCombined along axis 0:\n", matrix_combined_axis0)

matrix_combined_axis1 = np.concatenate((matrix, matrix2), axis=1)
print("\nCombined along axis 1:\n", matrix_combined_axis1)

First Matrix:
 [[9 1 6]
 [1 8 0]
 [4 6 1]]

Second Matrix:
 [[9 2 3]
 [3 0 1]
 [2 1 3]]

Combined along axis 0:
 [[9 1 6]
 [1 8 0]
 [4 6 1]
 [9 2 3]
 [3 0 1]
 [2 1 3]]

Combined along axis 1:
 [[9 1 6 9 2 3]
 [1 8 0 3 0 1]
 [4 6 1 2 1 3]]


In [16]:
matrix_added = matrix + matrix2
print("\nElement-wise Addition:\n", matrix_added)

matrix_subtracted = matrix - matrix2
print("\nElement-wise Subtraction:\n", matrix_subtracted)

matrix_multiplied = matrix * matrix2
print("\nElement-wise Multiplication:\n", matrix_multiplied)


Element-wise Addition:
 [[18  3  9]
 [ 4  8  1]
 [ 6  7  4]]

Element-wise Subtraction:
 [[ 0 -1  3]
 [-2  8 -1]
 [ 2  5 -2]]

Element-wise Multiplication:
 [[81  2 18]
 [ 3  0  0]
 [ 8  6  3]]


In [17]:
array_1d = np.array([10, 20, 30])
print("1D Array:\n", array_1d)
print("\nOriginal 2D Matrix:\n", matrix)

matrix_broadcasted = matrix + array_1d
print("\n2D Matrix after Broadcasting Addition:\n", matrix_broadcasted)

1D Array:
 [10 20 30]

Original 2D Matrix:
 [[9 1 6]
 [1 8 0]
 [4 6 1]]

2D Matrix after Broadcasting Addition:
 [[19 21 36]
 [11 28 30]
 [14 26 31]]


In [18]:
print("Original Matrix:\n", matrix)

matrix_clipped = np.clip(matrix, 2, 8)
print("\nClipped Matrix (values between 2 and 8):\n", matrix_clipped)

Original Matrix:
 [[9 1 6]
 [1 8 0]
 [4 6 1]]

Clipped Matrix (values between 2 and 8):
 [[8 2 6]
 [2 8 2]
 [4 6 2]]


In [19]:
float_array = np.array([1.2, 2.5, 3.8])
print("Original Floating-Point Array:\n", float_array)

ceil_array = np.ceil(float_array)
print("\nArray after applying np.ceil:\n", ceil_array)

Original Floating-Point Array:
 [1.2 2.5 3.8]

Array after applying np.ceil:
 [2. 3. 4.]


In [20]:
given_array = np.array([1, 6, 3, 8, 2, 9, 4, 7, 5])
print("Original Array:\n", given_array)

modified_array = np.where(given_array > 5, 100, given_array)
print("\nModified Array (elements > 5 replaced with 100):\n", modified_array)

Original Array:
 [1 6 3 8 2 9 4 7 5]

Modified Array (elements > 5 replaced with 100):
 [  1 100   3 100   2 100   4 100   5]


In [21]:
matrix_a = np.array([[1, 2],
                     [3, 4]])
print("Matrix A:\n", matrix_a)

matrix_b = np.array([[5, 6],
                     [7, 8]])
print("\nMatrix B:\n", matrix_b)

dot_product = np.dot(matrix_a, matrix_b)
print("\nDot Product of Matrix A and Matrix B:\n", dot_product)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Dot Product of Matrix A and Matrix B:
 [[19 22]
 [43 50]]


In [ ]:
np.array([1, 2, 3]) is a 1D array (a single row of numbers), with a shape of (3,).
np.array([[1, 2, 3]]) is a 2D array (a matrix with one row and three columns), with a shape of (1, 3).